# Multiple Variable Linear Regression in Tensorflow

In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
rng = np.random

In [3]:
#Loading the basketball dataset to a Pandas Dataframe
data = np.loadtxt("data.txt", dtype="float32", encoding="utf8")
print(data)
print("\nShape of the Dataset:", data.shape)

[[2. 4. 2.]
 [4. 5. 1.]
 [7. 4. 2.]
 [1. 4. 2.]
 [2. 1. 1.]
 [9. 4. 2.]
 [0. 9. 1.]
 [5. 7. 1.]
 [3. 2. 2.]
 [2. 6. 2.]
 [1. 3. 1.]
 [5. 0. 2.]
 [7. 4. 2.]
 [8. 7. 1.]
 [3. 9. 1.]
 [1. 4. 2.]
 [5. 6. 2.]
 [3. 2. 2.]
 [2. 4. 2.]
 [6. 4. 2.]
 [4. 6. 2.]
 [7. 3. 1.]
 [8. 7. 1.]
 [9. 4. 2.]
 [1. 1. 1.]
 [5. 9. 1.]
 [3. 4. 2.]
 [6. 5. 1.]
 [4. 2. 2.]
 [8. 6. 2.]
 [9. 9. 1.]
 [1. 7. 1.]
 [2. 5. 1.]
 [5. 2. 2.]
 [4. 3. 1.]
 [8. 4. 2.]
 [6. 6. 2.]
 [2. 8. 2.]
 [5. 4. 2.]
 [9. 6. 2.]
 [7. 9. 1.]
 [4. 1. 1.]
 [7. 3. 1.]
 [4. 0. 2.]]

Shape of the Dataset: (44, 3)


In [5]:
X1_data = data[:,0]
X2_data = data[:,1]
Y_data = data[:,2]
n_samples = Y_data.shape
print(Y_data.shape)
X1_data.dtype

(44,)


dtype('float32')

Using Stochastic Gradient Descent

In [23]:
# Parameters
learning_rate = 0.001
training_epochs = 1000
display_step = 10

#tf Graph Input
X1 = tf.placeholder("float")
X2 = tf.placeholder("float")
Y = tf.placeholder("float")

# Set model weights
W1 = tf.Variable(rng.randn(), name="weight1")
W2 = tf.Variable(rng.randn(), name="weight2")
b = tf.Variable(rng.randn(), name="bias")

#Constructing a Linear Model with multiple attributes9
hypothesis = tf.add(tf.add(tf.multiply(W1, X1), tf.multiply(W2, X2)), b)

#Cost Function - Mean Squared Error
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Gradient descent
optimizer = tf.train.GradientDescentOptimizer(learning_rate)
train = optimizer.minimize(cost)

#Initializing the variables
init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)

    # Fit all training data
    for epoch in range(training_epochs):
        for (x1, x2, y) in zip(X1_data, X2_data, Y_data):
            sess.run(train, feed_dict={X1: x1, X2: x2, Y: y})
            c = sess.run(cost, feed_dict={X1: X1_data, X2: X2_data, Y: Y_data})
            #Display logs per epoch step
            if (epoch+1) % display_step == 0:
                c = sess.run(cost, feed_dict={X1: X1_data, X2: X2_data,  Y: Y_data})
                print("Epoch:", '%04d' % (epoch+1), "cost=", "{:.9f}".format(c), "Weights=", sess.run(W1), sess.run(W2), "Bias=", sess.run(b))
      
    print ("Optimization Finished!")
    training_cost = sess.run(cost, feed_dict={X1: X1_data, X2: X2_data, Y: Y_data})
    print ("Training cost=", training_cost, '\n')


Epoch: 0010 cost= 0.466778159 Weights= 0.12480186 0.06309726 Bias= 0.4625481
Epoch: 0010 cost= 0.470239460 Weights= 0.122583926 0.060324844 Bias= 0.46199363
Epoch: 0010 cost= 0.464678168 Weights= 0.1287246 0.0638338 Bias= 0.46287087
Epoch: 0010 cost= 0.464335918 Weights= 0.13103074 0.07305836 Bias= 0.465177
Epoch: 0010 cost= 0.464610606 Weights= 0.13182954 0.07345776 Bias= 0.4655764
Epoch: 0010 cost= 0.465140164 Weights= 0.13280383 0.073890775 Bias= 0.46568465
Epoch: 0010 cost= 0.464186162 Weights= 0.13280383 0.07153814 Bias= 0.46542326
Epoch: 0010 cost= 0.465325534 Weights= 0.12650174 0.06271521 Bias= 0.46416283
Epoch: 0010 cost= 0.462737590 Weights= 0.13268715 0.066838816 Bias= 0.46622464
Epoch: 0010 cost= 0.468804955 Weights= 0.13615662 0.07724723 Bias= 0.46795937
Epoch: 0010 cost= 0.469876796 Weights= 0.1364849 0.07823209 Bias= 0.46828765
Epoch: 0010 cost= 0.478755951 Weights= 0.14497778 0.07823209 Bias= 0.46998623
Epoch: 0010 cost= 0.485128433 Weights= 0.14780915 0.07985002 Bias= 

Epoch: 0040 cost= 0.331340104 Weights= 0.08949577 0.0205802 Bias= 0.89141077
Epoch: 0040 cost= 0.335455686 Weights= 0.08667741 0.017057251 Bias= 0.8907062
Epoch: 0040 cost= 0.330037266 Weights= 0.09275793 0.020531835 Bias= 0.8915748
Epoch: 0040 cost= 0.329279035 Weights= 0.09462501 0.028000154 Bias= 0.89344186
Epoch: 0040 cost= 0.329216033 Weights= 0.094182245 0.027778769 Bias= 0.8932205
Epoch: 0040 cost= 0.330108136 Weights= 0.096846685 0.028962962 Bias= 0.89351654
Epoch: 0040 cost= 0.329308242 Weights= 0.096846685 0.026187666 Bias= 0.89320815
Epoch: 0040 cost= 0.331263214 Weights= 0.09123913 0.018337091 Bias= 0.8920866
Epoch: 0040 cost= 0.328717500 Weights= 0.09602426 0.021527179 Bias= 0.89368165
Epoch: 0040 cost= 0.331859946 Weights= 0.09916469 0.03094846 Bias= 0.89525187
Epoch: 0040 cost= 0.331477046 Weights= 0.098990165 0.03042489 Bias= 0.89507735
Epoch: 0040 cost= 0.335657150 Weights= 0.10508988 0.03042489 Bias= 0.8962973
Epoch: 0040 cost= 0.341143161 Weights= 0.10853912 0.032395

Epoch: 0070 cost= 0.270404369 Weights= 0.06487439 -0.007406196 Bias= 1.1817273
Epoch: 0070 cost= 0.274881363 Weights= 0.061640836 -0.011448136 Bias= 1.1809189
Epoch: 0070 cost= 0.269543409 Weights= 0.06770827 -0.007981033 Bias= 1.1817857
Epoch: 0070 cost= 0.268702120 Weights= 0.06927313 -0.0017215912 Bias= 1.1833506
Epoch: 0070 cost= 0.268693715 Weights= 0.06799243 -0.0023619416 Bias= 1.1827102
Epoch: 0070 cost= 0.269454718 Weights= 0.07185893 -0.0006434957 Bias= 1.1831398
Epoch: 0070 cost= 0.268750787 Weights= 0.07185893 -0.0038357666 Bias= 1.1827852
Epoch: 0070 cost= 0.271119237 Weights= 0.066706635 -0.01104898 Bias= 1.1817547
Epoch: 0070 cost= 0.268765330 Weights= 0.070547976 -0.008488086 Bias= 1.1830351
Epoch: 0070 cost= 0.270222634 Weights= 0.07345516 0.0002334835 Bias= 1.1844888
Epoch: 0070 cost= 0.269462079 Weights= 0.072937876 -0.0013183827 Bias= 1.1839715
Epoch: 0070 cost= 0.271411926 Weights= 0.07745127 -0.0013183827 Bias= 1.1848742
Epoch: 0070 cost= 0.275852650 Weights= 0.08

Epoch: 0100 cost= 0.243237317 Weights= 0.048207667 -0.026350765 Bias= 1.3782485
Epoch: 0100 cost= 0.247923315 Weights= 0.044693064 -0.030744018 Bias= 1.3773698
Epoch: 0100 cost= 0.242639631 Weights= 0.050751634 -0.02728198 Bias= 1.3782352
Epoch: 0100 cost= 0.241787285 Weights= 0.052111916 -0.02184085 Bias= 1.3795955
Epoch: 0100 cost= 0.241944790 Weights= 0.050264 -0.022764808 Bias= 1.3786715
Epoch: 0100 cost= 0.242428795 Weights= 0.05494421 -0.020684713 Bias= 1.3791915
Epoch: 0100 cost= 0.241821870 Weights= 0.05494421 -0.024159236 Bias= 1.3788055
Epoch: 0100 cost= 0.244412884 Weights= 0.050100088 -0.030941004 Bias= 1.3778367
Epoch: 0100 cost= 0.242275327 Weights= 0.05330256 -0.028806023 Bias= 1.3789042
Epoch: 0100 cost= 0.242724180 Weights= 0.05605187 -0.020558102 Bias= 1.3802788
Epoch: 0100 cost= 0.241989523 Weights= 0.055302557 -0.022806041 Bias= 1.3795295
Epoch: 0100 cost= 0.242885724 Weights= 0.058742136 -0.022806041 Bias= 1.3802174
Epoch: 0100 cost= 0.246390760 Weights= 0.0629395 

Epoch: 0130 cost= 0.231300071 Weights= 0.036925815 -0.03917451 Bias= 1.5112755
Epoch: 0130 cost= 0.236111104 Weights= 0.033220965 -0.04380557 Bias= 1.5103493
Epoch: 0130 cost= 0.230864108 Weights= 0.03927353 -0.040346958 Bias= 1.5112139
Epoch: 0130 cost= 0.230024949 Weights= 0.040495332 -0.035459753 Bias= 1.5124357
Epoch: 0130 cost= 0.230353877 Weights= 0.038263466 -0.036575686 Bias= 1.5113198
Epoch: 0130 cost= 0.230564162 Weights= 0.043494478 -0.034250792 Bias= 1.511901
Epoch: 0130 cost= 0.230037555 Weights= 0.043494478 -0.037916385 Bias= 1.5114937
Epoch: 0130 cost= 0.232752860 Weights= 0.038858965 -0.044406105 Bias= 1.5105666
Epoch: 0130 cost= 0.230801448 Weights= 0.04162898 -0.04255943 Bias= 1.51149
Epoch: 0130 cost= 0.230628237 Weights= 0.044271413 -0.034632124 Bias= 1.5128112
Epoch: 0130 cost= 0.230040118 Weights= 0.04336504 -0.037351243 Bias= 1.5119048
Epoch: 0130 cost= 0.230432123 Weights= 0.04607774 -0.037351243 Bias= 1.5124474
Epoch: 0130 cost= 0.233199224 Weights= 0.050479528

Epoch: 0160 cost= 0.226176128 Weights= 0.029289017 -0.047855034 Bias= 1.6013229
Epoch: 0160 cost= 0.231064364 Weights= 0.025455385 -0.052647073 Bias= 1.6003644
Epoch: 0160 cost= 0.225842133 Weights= 0.031503893 -0.049190782 Bias= 1.6012285
Epoch: 0160 cost= 0.225021362 Weights= 0.032631956 -0.044678535 Bias= 1.6023566
Epoch: 0160 cost= 0.225493446 Weights= 0.030140188 -0.045924418 Bias= 1.6011107
Epoch: 0160 cost= 0.225478873 Weights= 0.035744045 -0.043433815 Bias= 1.6017333
Epoch: 0160 cost= 0.225013390 Weights= 0.035744045 -0.04722874 Bias= 1.6013117
Epoch: 0160 cost= 0.227800786 Weights= 0.031249737 -0.05352077 Bias= 1.6004128
Epoch: 0160 cost= 0.225993544 Weights= 0.033727013 -0.05186925 Bias= 1.6012386
Epoch: 0160 cost= 0.225426972 Weights= 0.036297105 -0.044158977 Bias= 1.6025237
Epoch: 0160 cost= 0.224997222 Weights= 0.03528442 -0.04719704 Bias= 1.601511
Epoch: 0160 cost= 0.225143656 Weights= 0.037505087 -0.04719704 Bias= 1.6019552
Epoch: 0160 cost= 0.227363363 Weights= 0.042045

Epoch: 0190 cost= 0.224062383 Weights= 0.024119535 -0.053731035 Bias= 1.6622773
Epoch: 0190 cost= 0.228999436 Weights= 0.020198733 -0.05863204 Bias= 1.6612971
Epoch: 0190 cost= 0.223793969 Weights= 0.026244491 -0.05517732 Bias= 1.6621608
Epoch: 0190 cost= 0.222989947 Weights= 0.0273091 -0.05091889 Bias= 1.6632254
Epoch: 0190 cost= 0.223571360 Weights= 0.0246414 -0.05225274 Bias= 1.6618916
Epoch: 0190 cost= 0.223386437 Weights= 0.030497644 -0.049649965 Bias= 1.6625422
Epoch: 0190 cost= 0.222965464 Weights= 0.030497644 -0.05353243 Bias= 1.6621108
Epoch: 0190 cost= 0.225796118 Weights= 0.026098924 -0.05969064 Bias= 1.661231
Epoch: 0190 cost= 0.224094778 Weights= 0.028378045 -0.058171224 Bias= 1.6619908
Epoch: 0190 cost= 0.223274693 Weights= 0.030899167 -0.050607856 Bias= 1.6632513
Epoch: 0190 cost= 0.222979203 Weights= 0.029814513 -0.05386182 Bias= 1.6621666
Epoch: 0190 cost= 0.223003298 Weights= 0.031702124 -0.05386182 Bias= 1.6625441
Epoch: 0190 cost= 0.224830493 Weights= 0.03633596 -0.

Epoch: 0220 cost= 0.223252282 Weights= 0.02062023 -0.05770857 Bias= 1.7035384
Epoch: 0220 cost= 0.228220761 Weights= 0.01664042 -0.06268334 Bias= 1.7025435
Epoch: 0220 cost= 0.223026663 Weights= 0.022684317 -0.05922968 Bias= 1.7034069
Epoch: 0220 cost= 0.222235978 Weights= 0.023705972 -0.05514306 Bias= 1.7044286
Epoch: 0220 cost= 0.222897112 Weights= 0.020919181 -0.056536455 Bias= 1.7030351
Epoch: 0220 cost= 0.222588599 Weights= 0.026946265 -0.05385775 Bias= 1.7037048
Epoch: 0220 cost= 0.222199097 Weights= 0.026946265 -0.05779948 Bias= 1.7032669
Epoch: 0220 cost= 0.225056514 Weights= 0.022612248 -0.06386711 Bias= 1.7024001
Epoch: 0220 cost= 0.223430693 Weights= 0.024757233 -0.062437117 Bias= 1.7031151
Epoch: 0220 cost= 0.222444832 Weights= 0.027245205 -0.0549732 Bias= 1.704359
Epoch: 0220 cost= 0.222252622 Weights= 0.026111836 -0.05837331 Bias= 1.7032257
Epoch: 0220 cost= 0.222214028 Weights= 0.027773986 -0.05837331 Bias= 1.7035582
Epoch: 0220 cost= 0.223765507 Weights= 0.032471225 -0.

Epoch: 0250 cost= 0.222988322 Weights= 0.018251348 -0.06040123 Bias= 1.7314706
Epoch: 0250 cost= 0.227977410 Weights= 0.014231591 -0.06542593 Bias= 1.7304657
Epoch: 0250 cost= 0.222790971 Weights= 0.020274227 -0.061972998 Bias= 1.7313288
Epoch: 0250 cost= 0.222010270 Weights= 0.021266805 -0.058002688 Bias= 1.7323214
Epoch: 0250 cost= 0.222727910 Weights= 0.018399395 -0.059436392 Bias= 1.7308877
Epoch: 0250 cost= 0.222331956 Weights= 0.024542136 -0.056706283 Bias= 1.7315701
Epoch: 0250 cost= 0.221964419 Weights= 0.024542136 -0.060688127 Bias= 1.7311277
Epoch: 0250 cost= 0.224838823 Weights= 0.02025192 -0.06669443 Bias= 1.7302697
Epoch: 0250 cost= 0.223265871 Weights= 0.022306101 -0.06532498 Bias= 1.7309544
Epoch: 0250 cost= 0.222170398 Weights= 0.024771634 -0.057928376 Bias= 1.7321872
Epoch: 0250 cost= 0.222053826 Weights= 0.023605287 -0.06142742 Bias= 1.7310208
Epoch: 0250 cost= 0.221981987 Weights= 0.025114816 -0.06142742 Bias= 1.7313228
Epoch: 0250 cost= 0.223342165 Weights= 0.029854

Epoch: 0280 cost= 0.222940028 Weights= 0.016647996 -0.062223714 Bias= 1.750376
Epoch: 0280 cost= 0.227942720 Weights= 0.012601201 -0.06728221 Bias= 1.7493643
Epoch: 0280 cost= 0.222761452 Weights= 0.018642988 -0.06382976 Bias= 1.7502273
Epoch: 0280 cost= 0.221987873 Weights= 0.019615885 -0.059938166 Bias= 1.7512002
Epoch: 0280 cost= 0.222745001 Weights= 0.016693909 -0.061399154 Bias= 1.7497392
Epoch: 0280 cost= 0.222288072 Weights= 0.022914931 -0.058634255 Bias= 1.7504303
Epoch: 0280 cost= 0.221935749 Weights= 0.022914931 -0.06264325 Bias= 1.7499849
Epoch: 0280 cost= 0.224821091 Weights= 0.018654363 -0.068608046 Bias= 1.7491328
Epoch: 0280 cost= 0.223284736 Weights= 0.020647084 -0.06727956 Bias= 1.749797
Epoch: 0280 cost= 0.222116292 Weights= 0.02309743 -0.05992853 Bias= 1.7510221
Epoch: 0280 cost= 0.222053543 Weights= 0.021908762 -0.06349453 Bias= 1.7498335
Epoch: 0280 cost= 0.221963421 Weights= 0.02331499 -0.06349453 Bias= 1.7501147
Epoch: 0280 cost= 0.223192021 Weights= 0.02808421 -

Epoch: 0310 cost= 0.222967014 Weights= 0.015562686 -0.063457355 Bias= 1.7631733
Epoch: 0310 cost= 0.227978766 Weights= 0.011497589 -0.068538725 Bias= 1.7621571
Epoch: 0310 cost= 0.222801015 Weights= 0.017538795 -0.06508661 Bias= 1.7630202
Epoch: 0310 cost= 0.222032502 Weights= 0.01849837 -0.06124831 Bias= 1.7639797
Epoch: 0310 cost= 0.222816855 Weights= 0.015539458 -0.062727764 Bias= 1.7625002
Epoch: 0310 cost= 0.222317934 Weights= 0.021813463 -0.059939317 Bias= 1.7631973
Epoch: 0310 cost= 0.221975982 Weights= 0.021813463 -0.0639667 Bias= 1.7627498
Epoch: 0310 cost= 0.224868476 Weights= 0.017572962 -0.0699034 Bias= 1.7619017
Epoch: 0310 cost= 0.223357216 Weights= 0.019524079 -0.06860266 Bias= 1.7625521
Epoch: 0310 cost= 0.222140029 Weights= 0.021964142 -0.06128247 Bias= 1.7637721
Epoch: 0310 cost= 0.222114861 Weights= 0.020760365 -0.064893804 Bias= 1.7625684
Epoch: 0310 cost= 0.222014278 Weights= 0.022096664 -0.064893804 Bias= 1.7628356
Epoch: 0310 cost= 0.223152891 Weights= 0.02688554

Epoch: 0340 cost= 0.223012701 Weights= 0.014827917 -0.06429257 Bias= 1.7718371
Epoch: 0340 cost= 0.228030488 Weights= 0.01075043 -0.06938943 Bias= 1.7708178
Epoch: 0340 cost= 0.222855106 Weights= 0.016791247 -0.065937534 Bias= 1.7716807
Epoch: 0340 cost= 0.222090095 Weights= 0.017741803 -0.06213531 Bias= 1.7726313
Epoch: 0340 cost= 0.222893178 Weights= 0.014757885 -0.063627265 Bias= 1.7711394
Epoch: 0340 cost= 0.222365394 Weights= 0.021067763 -0.060822874 Bias= 1.7718405
Epoch: 0340 cost= 0.222030535 Weights= 0.021067763 -0.0648627 Bias= 1.7713916
Epoch: 0340 cost= 0.224927798 Weights= 0.016840847 -0.07078038 Bias= 1.7705462
Epoch: 0340 cost= 0.223433718 Weights= 0.0187638 -0.06949841 Bias= 1.7711872
Epoch: 0340 cost= 0.222183719 Weights= 0.021196902 -0.062199105 Bias= 1.7724037
Epoch: 0340 cost= 0.222184569 Weights= 0.019982895 -0.06584112 Bias= 1.7711897
Epoch: 0340 cost= 0.222077802 Weights= 0.021271855 -0.06584112 Bias= 1.7714475
Epoch: 0340 cost= 0.223155037 Weights= 0.026074052 -

Epoch: 0370 cost= 0.223056123 Weights= 0.014330532 -0.06485789 Bias= 1.7777017
Epoch: 0370 cost= 0.228077993 Weights= 0.010244658 -0.069965236 Bias= 1.7766802
Epoch: 0370 cost= 0.222904220 Weights= 0.016285213 -0.06651349 Bias= 1.7775432
Epoch: 0370 cost= 0.222141609 Weights= 0.017229663 -0.06273569 Bias= 1.7784877
Epoch: 0370 cost= 0.222957462 Weights= 0.014228817 -0.06423611 Bias= 1.7769873
Epoch: 0370 cost= 0.222409979 Weights= 0.020562977 -0.06142093 Bias= 1.7776911
Epoch: 0370 cost= 0.222079992 Weights= 0.020562977 -0.065469176 Bias= 1.7772413
Epoch: 0370 cost= 0.224980399 Weights= 0.016345257 -0.071373984 Bias= 1.7763978
Epoch: 0370 cost= 0.223498046 Weights= 0.018249143 -0.070104726 Bias= 1.7770325
Epoch: 0370 cost= 0.222225964 Weights= 0.020677533 -0.062819555 Bias= 1.7782466
Epoch: 0370 cost= 0.222244680 Weights= 0.019456603 -0.06648235 Bias= 1.7770257
Epoch: 0370 cost= 0.222134128 Weights= 0.020713516 -0.06648235 Bias= 1.7772771
Epoch: 0370 cost= 0.223169580 Weights= 0.025524

Epoch: 0400 cost= 0.223091274 Weights= 0.013993725 -0.06524073 Bias= 1.7816732
Epoch: 0400 cost= 0.228115901 Weights= 0.00990217 -0.07035518 Bias= 1.7806503
Epoch: 0400 cost= 0.222943246 Weights= 0.015942544 -0.06690353 Bias= 1.7815132
Epoch: 0400 cost= 0.222182259 Weights= 0.016882861 -0.06314226 Bias= 1.7824535
Epoch: 0400 cost= 0.223006830 Weights= 0.013870553 -0.06464842 Bias= 1.7809473
Epoch: 0400 cost= 0.222445920 Weights= 0.020221157 -0.061825927 Bias= 1.7816529
Epoch: 0400 cost= 0.222119197 Weights= 0.020221157 -0.06587988 Bias= 1.7812024
Epoch: 0400 cost= 0.225021750 Weights= 0.016009666 -0.071775965 Bias= 1.7803601
Epoch: 0400 cost= 0.223547325 Weights= 0.017900642 -0.07051531 Bias= 1.7809905
Epoch: 0400 cost= 0.222260386 Weights= 0.020325843 -0.06323971 Bias= 1.7822031
Epoch: 0400 cost= 0.222291321 Weights= 0.019100223 -0.06691657 Bias= 1.7809775
Epoch: 0400 cost= 0.222178370 Weights= 0.020335438 -0.06691657 Bias= 1.7812245
Epoch: 0400 cost= 0.223185450 Weights= 0.02515275 -

Epoch: 0430 cost= 0.223117694 Weights= 0.013765913 -0.06549968 Bias= 1.7843596
Epoch: 0430 cost= 0.228144169 Weights= 0.009670515 -0.07061893 Bias= 1.7833357
Epoch: 0430 cost= 0.222972214 Weights= 0.015710764 -0.06716736 Bias= 1.7841985
Epoch: 0430 cost= 0.222212374 Weights= 0.016648283 -0.06341728 Bias= 1.785136
Epoch: 0430 cost= 0.223042861 Weights= 0.013628222 -0.06492731 Bias= 1.783626
Epoch: 0430 cost= 0.222472861 Weights= 0.01998995 -0.062099874 Bias= 1.7843329
Epoch: 0430 cost= 0.222148404 Weights= 0.01998995 -0.066157684 Bias= 1.783882
Epoch: 0430 cost= 0.225052312 Weights= 0.015782671 -0.072047874 Bias= 1.7830405
Epoch: 0430 cost= 0.223583356 Weights= 0.017664915 -0.07079305 Bias= 1.7836679
Epoch: 0430 cost= 0.222286358 Weights= 0.020087957 -0.06352392 Bias= 1.7848794
Epoch: 0430 cost= 0.222325549 Weights= 0.018859167 -0.067210294 Bias= 1.7836506
Epoch: 0430 cost= 0.222211108 Weights= 0.020079702 -0.067210294 Bias= 1.7838948
Epoch: 0430 cost= 0.223198950 Weights= 0.02490114 -0

Epoch: 0460 cost= 0.223136798 Weights= 0.013611856 -0.06567478 Bias= 1.7861757
Epoch: 0460 cost= 0.228164539 Weights= 0.009513862 -0.07079727 Bias= 1.7851512
Epoch: 0460 cost= 0.222993076 Weights= 0.015554034 -0.067345746 Bias= 1.7860141
Epoch: 0460 cost= 0.222233966 Weights= 0.016489664 -0.06360323 Bias= 1.7869498
Epoch: 0460 cost= 0.223068461 Weights= 0.0134643605 -0.065115884 Bias= 1.7854371
Epoch: 0460 cost= 0.222492307 Weights= 0.01983361 -0.062285107 Bias= 1.7861449
Epoch: 0460 cost= 0.222169310 Weights= 0.01983361 -0.06634553 Bias= 1.7856936
Epoch: 0460 cost= 0.225074232 Weights= 0.01562918 -0.07223173 Bias= 1.7848527
Epoch: 0460 cost= 0.223608881 Weights= 0.01750552 -0.07098084 Bias= 1.7854782
Epoch: 0460 cost= 0.222305119 Weights= 0.019927103 -0.06371609 Bias= 1.786689
Epoch: 0460 cost= 0.222349942 Weights= 0.018696167 -0.0674089 Bias= 1.7854581
Epoch: 0460 cost= 0.222234547 Weights= 0.019906778 -0.0674089 Bias= 1.7857002
Epoch: 0460 cost= 0.223209336 Weights= 0.02473101 -0.06

Epoch: 0490 cost= 0.223150253 Weights= 0.013507605 -0.06579332 Bias= 1.7874051
Epoch: 0490 cost= 0.228178784 Weights= 0.009407853 -0.07091801 Bias= 1.7863802
Epoch: 0490 cost= 0.223007694 Weights= 0.01544797 -0.06746651 Bias= 1.787243
Epoch: 0490 cost= 0.222249120 Weights= 0.01638232 -0.063729115 Bias= 1.7881774
Epoch: 0490 cost= 0.223086357 Weights= 0.013353468 -0.06524354 Bias= 1.7866629
Epoch: 0490 cost= 0.222505957 Weights= 0.01972781 -0.062410504 Bias= 1.7873712
Epoch: 0490 cost= 0.222184002 Weights= 0.01972781 -0.06647269 Bias= 1.7869198
Epoch: 0490 cost= 0.225089595 Weights= 0.015525309 -0.07235619 Bias= 1.7860793
Epoch: 0490 cost= 0.223626703 Weights= 0.017397651 -0.07110796 Bias= 1.7867033
Epoch: 0490 cost= 0.222318351 Weights= 0.019818248 -0.06384617 Bias= 1.7879137
Epoch: 0490 cost= 0.222367033 Weights= 0.01858586 -0.06754333 Bias= 1.7866813
Epoch: 0490 cost= 0.222250953 Weights= 0.019789755 -0.06754333 Bias= 1.7869221
Epoch: 0490 cost= 0.223216951 Weights= 0.024615876 -0.06

Epoch: 0520 cost= 0.223159656 Weights= 0.013436871 -0.06587369 Bias= 1.7882391
Epoch: 0520 cost= 0.228188753 Weights= 0.009335925 -0.070999876 Bias= 1.7872139
Epoch: 0520 cost= 0.223017886 Weights= 0.015376003 -0.0675484 Bias= 1.7880768
Epoch: 0520 cost= 0.222259656 Weights= 0.016309485 -0.063814476 Bias= 1.7890103
Epoch: 0520 cost= 0.223098710 Weights= 0.013278225 -0.0653301 Bias= 1.7874947
Epoch: 0520 cost= 0.222515523 Weights= 0.019656017 -0.06249553 Bias= 1.7882034
Epoch: 0520 cost= 0.222194239 Weights= 0.019656017 -0.06655891 Bias= 1.7877519
Epoch: 0520 cost= 0.225100264 Weights= 0.015454821 -0.07244059 Bias= 1.7869117
Epoch: 0520 cost= 0.223639056 Weights= 0.017324451 -0.071194164 Bias= 1.787535
Epoch: 0520 cost= 0.222327605 Weights= 0.019744376 -0.06393439 Bias= 1.7887449
Epoch: 0520 cost= 0.222378865 Weights= 0.018511003 -0.06763451 Bias= 1.7875116
Epoch: 0520 cost= 0.222262383 Weights= 0.019710336 -0.06763451 Bias= 1.7877514
Epoch: 0520 cost= 0.223222390 Weights= 0.024537737 -

Epoch: 0550 cost= 0.223166093 Weights= 0.013389121 -0.065928 Bias= 1.7888023
Epoch: 0550 cost= 0.228195608 Weights= 0.00928737 -0.07105519 Bias= 1.7877768
Epoch: 0550 cost= 0.223024845 Weights= 0.015327424 -0.06760373 Bias= 1.7886397
Epoch: 0550 cost= 0.222266898 Weights= 0.01626032 -0.06387214 Bias= 1.7895726
Epoch: 0550 cost= 0.223107189 Weights= 0.013227436 -0.06538858 Bias= 1.7880561
Epoch: 0550 cost= 0.222522065 Weights= 0.019607559 -0.06255297 Bias= 1.7887651
Epoch: 0550 cost= 0.222201288 Weights= 0.019607559 -0.06661716 Bias= 1.7883135
Epoch: 0550 cost= 0.225107566 Weights= 0.0154072475 -0.0724976 Bias= 1.7874734
Epoch: 0550 cost= 0.223647535 Weights= 0.017275048 -0.0712524 Bias= 1.7880961
Epoch: 0550 cost= 0.222333953 Weights= 0.019694522 -0.06399398 Bias= 1.7893058
Epoch: 0550 cost= 0.222387016 Weights= 0.018460486 -0.067696095 Bias= 1.7880718
Epoch: 0550 cost= 0.222270191 Weights= 0.019656744 -0.067696095 Bias= 1.788311
Epoch: 0550 cost= 0.223226160 Weights= 0.02448501 -0.064

Epoch: 0580 cost= 0.223170474 Weights= 0.013357036 -0.06596446 Bias= 1.7891806
Epoch: 0580 cost= 0.228200242 Weights= 0.009254743 -0.07109232 Bias= 1.7881551
Epoch: 0580 cost= 0.223029613 Weights= 0.015294779 -0.06764087 Bias= 1.7890179
Epoch: 0580 cost= 0.222271785 Weights= 0.01622728 -0.063910864 Bias= 1.7899504
Epoch: 0580 cost= 0.223112926 Weights= 0.013193305 -0.065427855 Bias= 1.7884334
Epoch: 0580 cost= 0.222526535 Weights= 0.019574992 -0.06259155 Bias= 1.7891425
Epoch: 0580 cost= 0.222206056 Weights= 0.019574992 -0.066656284 Bias= 1.7886908
Epoch: 0580 cost= 0.225112528 Weights= 0.015375273 -0.07253589 Bias= 1.7878509
Epoch: 0580 cost= 0.223653302 Weights= 0.017241845 -0.07129151 Bias= 1.788473
Epoch: 0580 cost= 0.222338289 Weights= 0.019661015 -0.064034 Bias= 1.7896826
Epoch: 0580 cost= 0.222392499 Weights= 0.018426532 -0.06773745 Bias= 1.7884481
Epoch: 0580 cost= 0.222275510 Weights= 0.019620724 -0.06773745 Bias= 1.788687
Epoch: 0580 cost= 0.223228738 Weights= 0.024449572 -0.

Epoch: 0610 cost= 0.223173440 Weights= 0.013335332 -0.06598909 Bias= 1.7894363
Epoch: 0610 cost= 0.228203386 Weights= 0.009232675 -0.071117416 Bias= 1.7884107
Epoch: 0610 cost= 0.223032847 Weights= 0.015272699 -0.06766597 Bias= 1.7892735
Epoch: 0610 cost= 0.222275123 Weights= 0.016204935 -0.06393703 Bias= 1.7902057
Epoch: 0610 cost= 0.223116830 Weights= 0.01317022 -0.065454386 Bias= 1.7886883
Epoch: 0610 cost= 0.222529560 Weights= 0.019552972 -0.06261761 Bias= 1.7893975
Epoch: 0610 cost= 0.222209305 Weights= 0.019552972 -0.06668271 Bias= 1.7889458
Epoch: 0610 cost= 0.225115925 Weights= 0.015353655 -0.072561756 Bias= 1.788106
Epoch: 0610 cost= 0.223657146 Weights= 0.017219394 -0.071317926 Bias= 1.7887279
Epoch: 0610 cost= 0.222341210 Weights= 0.019638358 -0.06406104 Bias= 1.7899374
Epoch: 0610 cost= 0.222396240 Weights= 0.018403573 -0.06776539 Bias= 1.7887026
Epoch: 0610 cost= 0.222279131 Weights= 0.019596368 -0.06776539 Bias= 1.7889411
Epoch: 0610 cost= 0.223230541 Weights= 0.02442561 

Epoch: 0640 cost= 0.223175570 Weights= 0.013320074 -0.066006444 Bias= 1.7896163
Epoch: 0640 cost= 0.228205621 Weights= 0.00921716 -0.07113509 Bias= 1.7885907
Epoch: 0640 cost= 0.223035112 Weights= 0.015257175 -0.06768365 Bias= 1.7894535
Epoch: 0640 cost= 0.222277507 Weights= 0.016189223 -0.06395546 Bias= 1.7903856
Epoch: 0640 cost= 0.223119602 Weights= 0.013153989 -0.06547308 Bias= 1.788868
Epoch: 0640 cost= 0.222531706 Weights= 0.019537482 -0.06263597 Bias= 1.7895772
Epoch: 0640 cost= 0.222211599 Weights= 0.019537482 -0.06670134 Bias= 1.7891256
Epoch: 0640 cost= 0.225118339 Weights= 0.015338445 -0.07257999 Bias= 1.7882857
Epoch: 0640 cost= 0.223659933 Weights= 0.0172036 -0.07133655 Bias= 1.7889074
Epoch: 0640 cost= 0.222343311 Weights= 0.019622419 -0.0640801 Bias= 1.7901168
Epoch: 0640 cost= 0.222398892 Weights= 0.018387422 -0.06778509 Bias= 1.7888818
Epoch: 0640 cost= 0.222281709 Weights= 0.019579234 -0.06778509 Bias= 1.7891202
Epoch: 0640 cost= 0.223231792 Weights= 0.024408752 -0.06

Epoch: 0670 cost= 0.223176971 Weights= 0.013309853 -0.066018075 Bias= 1.7897369
Epoch: 0670 cost= 0.228207156 Weights= 0.009206765 -0.071146935 Bias= 1.7887111
Epoch: 0670 cost= 0.223036677 Weights= 0.015246775 -0.0676955 Bias= 1.7895739
Epoch: 0670 cost= 0.222279087 Weights= 0.016178697 -0.06396781 Bias= 1.7905059
Epoch: 0670 cost= 0.223121464 Weights= 0.013143115 -0.0654856 Bias= 1.7889881
Epoch: 0670 cost= 0.222533166 Weights= 0.019527107 -0.06264827 Bias= 1.7896974
Epoch: 0670 cost= 0.222213134 Weights= 0.019527107 -0.0667138 Bias= 1.7892457
Epoch: 0670 cost= 0.225119919 Weights= 0.01532826 -0.07259219 Bias= 1.788406
Epoch: 0670 cost= 0.223661765 Weights= 0.017193021 -0.07134902 Bias= 1.7890276
Epoch: 0670 cost= 0.222344726 Weights= 0.019611744 -0.06409285 Bias= 1.790237
Epoch: 0670 cost= 0.222400665 Weights= 0.018376604 -0.06779827 Bias= 1.7890018
Epoch: 0670 cost= 0.222283423 Weights= 0.019567754 -0.06779827 Bias= 1.78924
Epoch: 0670 cost= 0.223232642 Weights= 0.024397457 -0.0650

Epoch: 0700 cost= 0.223178014 Weights= 0.01330246 -0.06602647 Bias= 1.789824
Epoch: 0700 cost= 0.228208244 Weights= 0.009199248 -0.07115549 Bias= 1.7887982
Epoch: 0700 cost= 0.223037764 Weights= 0.015239255 -0.06770406 Bias= 1.789661
Epoch: 0700 cost= 0.222280219 Weights= 0.016171087 -0.063976735 Bias= 1.7905929
Epoch: 0700 cost= 0.223122820 Weights= 0.0131352525 -0.06549465 Bias= 1.789075
Epoch: 0700 cost= 0.222534195 Weights= 0.019519605 -0.06265716 Bias= 1.7897844
Epoch: 0700 cost= 0.222214267 Weights= 0.019519605 -0.06672282 Bias= 1.7893327
Epoch: 0700 cost= 0.225121111 Weights= 0.015320893 -0.07260101 Bias= 1.788493
Epoch: 0700 cost= 0.223663107 Weights= 0.017185371 -0.071358025 Bias= 1.7891145
Epoch: 0700 cost= 0.222345740 Weights= 0.019604024 -0.06410207 Bias= 1.7903239
Epoch: 0700 cost= 0.222401962 Weights= 0.01836878 -0.0678078 Bias= 1.7890886
Epoch: 0700 cost= 0.222284660 Weights= 0.019559454 -0.0678078 Bias= 1.7893268
Epoch: 0700 cost= 0.223233268 Weights= 0.02438929 -0.0650

Epoch: 0730 cost= 0.223178715 Weights= 0.0132973 -0.06603235 Bias= 1.789885
Epoch: 0730 cost= 0.228208974 Weights= 0.009194 -0.07116148 Bias= 1.7888592
Epoch: 0730 cost= 0.223038569 Weights= 0.015234001 -0.06771005 Bias= 1.7897221
Epoch: 0730 cost= 0.222281039 Weights= 0.016165769 -0.06398298 Bias= 1.7906538
Epoch: 0730 cost= 0.223123774 Weights= 0.01312976 -0.06550098 Bias= 1.7891358
Epoch: 0730 cost= 0.222534955 Weights= 0.019514365 -0.06266338 Bias= 1.7898452
Epoch: 0730 cost= 0.222215071 Weights= 0.019514365 -0.06672913 Bias= 1.7893934
Epoch: 0730 cost= 0.225121886 Weights= 0.015315752 -0.07260719 Bias= 1.7885537
Epoch: 0730 cost= 0.223664060 Weights= 0.017180033 -0.071364336 Bias= 1.7891752
Epoch: 0730 cost= 0.222346440 Weights= 0.019598637 -0.06410853 Bias= 1.7903844
Epoch: 0730 cost= 0.222402856 Weights= 0.018363321 -0.06781447 Bias= 1.789149
Epoch: 0730 cost= 0.222285554 Weights= 0.019553665 -0.06781447 Bias= 1.7893871
Epoch: 0730 cost= 0.223233685 Weights= 0.024383597 -0.06505

Epoch: 0760 cost= 0.223179102 Weights= 0.013294722 -0.06603527 Bias= 1.7899151
Epoch: 0760 cost= 0.228209391 Weights= 0.009191381 -0.071164444 Bias= 1.7888893
Epoch: 0760 cost= 0.223038927 Weights= 0.015231384 -0.067713015 Bias= 1.7897521
Epoch: 0760 cost= 0.222281441 Weights= 0.016163122 -0.06398606 Bias= 1.7906839
Epoch: 0760 cost= 0.223124221 Weights= 0.013127025 -0.06550411 Bias= 1.7891659
Epoch: 0760 cost= 0.222535312 Weights= 0.019511757 -0.06266645 Bias= 1.7898753
Epoch: 0760 cost= 0.222215459 Weights= 0.019511757 -0.06673224 Bias= 1.7894235
Epoch: 0760 cost= 0.225122347 Weights= 0.015313191 -0.07261024 Bias= 1.7885838
Epoch: 0760 cost= 0.223664507 Weights= 0.017177375 -0.07136745 Bias= 1.7892052
Epoch: 0760 cost= 0.222346827 Weights= 0.019595955 -0.06411171 Bias= 1.7904145
Epoch: 0760 cost= 0.222403333 Weights= 0.018360604 -0.06781776 Bias= 1.7891791
Epoch: 0760 cost= 0.222285986 Weights= 0.019550782 -0.06781776 Bias= 1.7894171
Epoch: 0760 cost= 0.223233894 Weights= 0.02438076 

Epoch: 0790 cost= 0.223179296 Weights= 0.013293288 -0.06603691 Bias= 1.7899321
Epoch: 0790 cost= 0.228209600 Weights= 0.009189921 -0.07116612 Bias= 1.7889063
Epoch: 0790 cost= 0.223039165 Weights= 0.015229924 -0.06771469 Bias= 1.7897692
Epoch: 0790 cost= 0.222281680 Weights= 0.016161643 -0.063987814 Bias= 1.7907009
Epoch: 0790 cost= 0.223124489 Weights= 0.013125497 -0.065505885 Bias= 1.7891828
Epoch: 0790 cost= 0.222535506 Weights= 0.0195103 -0.0626682 Bias= 1.7898922
Epoch: 0790 cost= 0.222215652 Weights= 0.0195103 -0.06673401 Bias= 1.7894404
Epoch: 0790 cost= 0.225122541 Weights= 0.015311763 -0.072611965 Bias= 1.7886007
Epoch: 0790 cost= 0.223664805 Weights= 0.01717589 -0.071369216 Bias= 1.789222
Epoch: 0790 cost= 0.222347006 Weights= 0.019594457 -0.06411352 Bias= 1.7904313
Epoch: 0790 cost= 0.222403571 Weights= 0.018359087 -0.06781963 Bias= 1.7891959
Epoch: 0790 cost= 0.222286224 Weights= 0.019549174 -0.06781963 Bias= 1.789434
Epoch: 0790 cost= 0.223234028 Weights= 0.02437918 -0.065

Epoch: 0820 cost= 0.223179355 Weights= 0.013292851 -0.06603741 Bias= 1.7899373
Epoch: 0820 cost= 0.228209645 Weights= 0.009189478 -0.07116663 Bias= 1.7889115
Epoch: 0820 cost= 0.223039240 Weights= 0.01522948 -0.0677152 Bias= 1.7897743
Epoch: 0820 cost= 0.222281709 Weights= 0.016161194 -0.06398834 Bias= 1.790706
Epoch: 0820 cost= 0.223124564 Weights= 0.013125033 -0.06550642 Bias= 1.7891879
Epoch: 0820 cost= 0.222535565 Weights= 0.019509858 -0.06266872 Bias= 1.7898973
Epoch: 0820 cost= 0.222215742 Weights= 0.019509858 -0.06673454 Bias= 1.7894455
Epoch: 0820 cost= 0.225122601 Weights= 0.015311327 -0.07261248 Bias= 1.7886058
Epoch: 0820 cost= 0.223664895 Weights= 0.017175438 -0.07136974 Bias= 1.7892271
Epoch: 0820 cost= 0.222347036 Weights= 0.019594 -0.06411405 Bias= 1.7904364
Epoch: 0820 cost= 0.222403631 Weights= 0.018358624 -0.06782018 Bias= 1.789201
Epoch: 0820 cost= 0.222286269 Weights= 0.019548682 -0.06782018 Bias= 1.7894391
Epoch: 0820 cost= 0.223234072 Weights= 0.024378695 -0.06506

Epoch: 0850 cost= 0.223179519 Weights= 0.01329189 -0.066038504 Bias= 1.7899487
Epoch: 0850 cost= 0.228209823 Weights= 0.009188499 -0.071167745 Bias= 1.7889229
Epoch: 0850 cost= 0.223039389 Weights= 0.0152285 -0.067716315 Bias= 1.7897857
Epoch: 0850 cost= 0.222281873 Weights= 0.016160201 -0.063989505 Bias= 1.7907175
Epoch: 0850 cost= 0.223124743 Weights= 0.013124008 -0.065507606 Bias= 1.7891994
Epoch: 0850 cost= 0.222535715 Weights= 0.019508878 -0.06266989 Bias= 1.7899088
Epoch: 0850 cost= 0.222215891 Weights= 0.019508878 -0.06673572 Bias= 1.789457
Epoch: 0850 cost= 0.225122750 Weights= 0.015310364 -0.07261364 Bias= 1.7886173
Epoch: 0850 cost= 0.223665044 Weights= 0.017174438 -0.07137093 Bias= 1.7892386
Epoch: 0850 cost= 0.222347200 Weights= 0.01959299 -0.06411527 Bias= 1.7904478
Epoch: 0850 cost= 0.222403809 Weights= 0.0183576 -0.06782144 Bias= 1.7892125
Epoch: 0850 cost= 0.222286463 Weights= 0.019547595 -0.06782144 Bias= 1.7894504
Epoch: 0850 cost= 0.223234162 Weights= 0.024377625 -0.

Epoch: 0880 cost= 0.223179638 Weights= 0.013290739 -0.06603981 Bias= 1.7899623
Epoch: 0880 cost= 0.228209928 Weights= 0.009187329 -0.07116907 Bias= 1.7889365
Epoch: 0880 cost= 0.223039538 Weights= 0.015227327 -0.06771764 Bias= 1.7897993
Epoch: 0880 cost= 0.222282067 Weights= 0.016159015 -0.06399089 Bias= 1.7907311
Epoch: 0880 cost= 0.223124921 Weights= 0.013122782 -0.06550901 Bias= 1.789213
Epoch: 0880 cost= 0.222535864 Weights= 0.019507708 -0.06267126 Bias= 1.7899224
Epoch: 0880 cost= 0.222216040 Weights= 0.019507708 -0.066737115 Bias= 1.7894706
Epoch: 0880 cost= 0.225122929 Weights= 0.015309215 -0.072615005 Bias= 1.7886308
Epoch: 0880 cost= 0.223665237 Weights= 0.017173244 -0.071372315 Bias= 1.7892522
Epoch: 0880 cost= 0.222347349 Weights= 0.019591784 -0.064116694 Bias= 1.7904614
Epoch: 0880 cost= 0.222404018 Weights= 0.018356377 -0.06782291 Bias= 1.789226
Epoch: 0880 cost= 0.222286656 Weights= 0.019546298 -0.06782291 Bias= 1.789464
Epoch: 0880 cost= 0.223234236 Weights= 0.02437635 -

Epoch: 0910 cost= 0.223179772 Weights= 0.01328993 -0.066040695 Bias= 1.7899717
Epoch: 0910 cost= 0.228210077 Weights= 0.009186506 -0.07116997 Bias= 1.7889458
Epoch: 0910 cost= 0.223039672 Weights= 0.015226507 -0.06771854 Bias= 1.7898086
Epoch: 0910 cost= 0.222282186 Weights= 0.016158184 -0.06399183 Bias= 1.7907403
Epoch: 0910 cost= 0.223125085 Weights= 0.013121925 -0.06550996 Bias= 1.7892221
Epoch: 0910 cost= 0.222535953 Weights= 0.019506892 -0.0626722 Bias= 1.7899315
Epoch: 0910 cost= 0.222216144 Weights= 0.019506892 -0.06673807 Bias= 1.7894797
Epoch: 0910 cost= 0.225123063 Weights= 0.015308415 -0.07261594 Bias= 1.78864
Epoch: 0910 cost= 0.223665416 Weights= 0.017172415 -0.07137327 Bias= 1.7892613
Epoch: 0910 cost= 0.222347453 Weights= 0.019590948 -0.06411767 Bias= 1.7904706
Epoch: 0910 cost= 0.222404152 Weights= 0.01835553 -0.067823924 Bias= 1.7892352
Epoch: 0910 cost= 0.222286791 Weights= 0.0195454 -0.067823924 Bias= 1.7894732
Epoch: 0910 cost= 0.223234281 Weights= 0.024375467 -0.06

Epoch: 0940 cost= 0.223179802 Weights= 0.013289824 -0.06604087 Bias= 1.7899731
Epoch: 0940 cost= 0.228210121 Weights= 0.0091864 -0.07117015 Bias= 1.7889472
Epoch: 0940 cost= 0.223039716 Weights= 0.0152264 -0.06771872 Bias= 1.7898101
Epoch: 0940 cost= 0.222282186 Weights= 0.016158078 -0.063992016 Bias= 1.7907417
Epoch: 0940 cost= 0.223125115 Weights= 0.0131218145 -0.06551015 Bias= 1.7892236
Epoch: 0940 cost= 0.222535983 Weights= 0.019506788 -0.062672384 Bias= 1.789933
Epoch: 0940 cost= 0.222216189 Weights= 0.019506788 -0.066738255 Bias= 1.7894812
Epoch: 0940 cost= 0.225123107 Weights= 0.015308315 -0.072616115 Bias= 1.7886415
Epoch: 0940 cost= 0.223665431 Weights= 0.01717231 -0.071373455 Bias= 1.7892628
Epoch: 0940 cost= 0.222347453 Weights= 0.019590843 -0.06411786 Bias= 1.790472
Epoch: 0940 cost= 0.222404182 Weights= 0.018355425 -0.06782411 Bias= 1.7892367
Epoch: 0940 cost= 0.222286806 Weights= 0.019545289 -0.06782411 Bias= 1.7894746
Epoch: 0940 cost= 0.223234311 Weights= 0.024375357 -0

Epoch: 0970 cost= 0.223179802 Weights= 0.013289824 -0.06604087 Bias= 1.7899731
Epoch: 0970 cost= 0.228210121 Weights= 0.0091864 -0.07117015 Bias= 1.7889472
Epoch: 0970 cost= 0.223039716 Weights= 0.0152264 -0.06771872 Bias= 1.7898101
Epoch: 0970 cost= 0.222282186 Weights= 0.016158078 -0.063992016 Bias= 1.7907417
Epoch: 0970 cost= 0.223125115 Weights= 0.0131218145 -0.06551015 Bias= 1.7892236
Epoch: 0970 cost= 0.222535983 Weights= 0.019506788 -0.062672384 Bias= 1.789933
Epoch: 0970 cost= 0.222216189 Weights= 0.019506788 -0.066738255 Bias= 1.7894812
Epoch: 0970 cost= 0.225123107 Weights= 0.015308315 -0.072616115 Bias= 1.7886415
Epoch: 0970 cost= 0.223665431 Weights= 0.01717231 -0.071373455 Bias= 1.7892628
Epoch: 0970 cost= 0.222347453 Weights= 0.019590843 -0.06411786 Bias= 1.790472
Epoch: 0970 cost= 0.222404182 Weights= 0.018355425 -0.06782411 Bias= 1.7892367
Epoch: 0970 cost= 0.222286806 Weights= 0.019545289 -0.06782411 Bias= 1.7894746
Epoch: 0970 cost= 0.223234311 Weights= 0.024375357 -0

Epoch: 1000 cost= 0.223179802 Weights= 0.013289824 -0.06604087 Bias= 1.7899731
Epoch: 1000 cost= 0.228210121 Weights= 0.0091864 -0.07117015 Bias= 1.7889472
Epoch: 1000 cost= 0.223039716 Weights= 0.0152264 -0.06771872 Bias= 1.7898101
Epoch: 1000 cost= 0.222282186 Weights= 0.016158078 -0.063992016 Bias= 1.7907417
Epoch: 1000 cost= 0.223125115 Weights= 0.0131218145 -0.06551015 Bias= 1.7892236
Epoch: 1000 cost= 0.222535983 Weights= 0.019506788 -0.062672384 Bias= 1.789933
Epoch: 1000 cost= 0.222216189 Weights= 0.019506788 -0.066738255 Bias= 1.7894812
Epoch: 1000 cost= 0.225123107 Weights= 0.015308315 -0.072616115 Bias= 1.7886415
Epoch: 1000 cost= 0.223665431 Weights= 0.01717231 -0.071373455 Bias= 1.7892628
Epoch: 1000 cost= 0.222347453 Weights= 0.019590843 -0.06411786 Bias= 1.790472
Epoch: 1000 cost= 0.222404182 Weights= 0.018355425 -0.06782411 Bias= 1.7892367
Epoch: 1000 cost= 0.222286806 Weights= 0.019545289 -0.06782411 Bias= 1.7894746
Epoch: 1000 cost= 0.223234311 Weights= 0.024375357 -0